function(cli_apply_sanitizers target)
    if(MSVC)
        return()
    endif()

    set(_san "")
    if(CLI_ENABLE_ASAN)
        list(APPEND _san address)
    endif()
    if(CLI_ENABLE_UBSAN)
        list(APPEND _san undefined)
    endif()

    if(_san)
        string(REPLACE ";" "," _san_csv "${_san}")
        target_compile_options(${target} PRIVATE -fsanitize=${_san_csv} -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=${_san_csv})
    endif()
endfunction()
